---
# Routeur du voisin

# Indique comment contacter la cible
# ansible_host : 192.168.103.129 <- commenté car déjà dans hosts
# Comptes par défaut
ansible_user : cisco
ansible_password : cisco123!
# Propre à cisco
ansible_connection : network_cli
ansible_network_os : cisco.ios.ios
