- name: Acte 1 - essai csr1000
  # On cible le nom défini dans ton inventaire
  hosts: CSR1000
  gather_facts: false

  tasks:
    - name: Récupère la configuration
      # Utilisation du module Cisco pour le show run
      cisco.ios.ios_command:
        commands: show running-config
      register: config

    - name: Enregistre la configuration
      # Copie le résultat dans un fichier texte local
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "show_run_{{ inventory_hostname }}.txt"
